# Generated by Django 4.2.5 on 2023-09-17 22:51

import auth_app.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_basemodel_remove_profile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='basemodel_ptr',
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.UUIDField(default=auth_app.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
